### PR TITLE
TT-10045 feat: Add parameter for key hashing algorithm

### LINKED ISSUE #109: Unable to change key hashing algorithm
See https://github.com/TykTechnologies/tyk/issues/5486

### PR DESCRIPTION
**Pull request by jakub-bochenski**
## Description
Parametrize the TYK_GW_HASHKEYFUNCTION value

## Related Issue
Resolves #109

## Motivation and Context
See #109 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by caroltyk** [comment]
Hi @jakub-bochenski thanks a lot for your contribution, it looks good!

The only thing I'd like to modify is to set a default value so that the chart would be backward compatible with existing values.yaml, like this

`{{ .Values.gateway.hashKeyFunction | default "murmur128" }}`

**Comment by jakub-bochenski** [comment]
umm.. it's set in the values file already

**Comment by jakub-bochenski** [comment]
@caroltyk  bump?

Default values should be specified in values.yaml

> In an actual chart, all static default values should live in the values.yaml,
and should not be repeated using the default command (otherwise they would be
redundant). However, the default command is perfect for computed values, which
cannot be declared inside values.yaml.

https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function

**Review by buraksekili — APPROVED** [review]

**Comment by jakub-bochenski** [comment]
I don't think the test failure is cause by my change

```
W0912 16:15:18.962970    9700 warnings.go:70] spec.template.spec.containers[0].env[38].name: duplicate name "TYK_GW_SECRET"
Error: INSTALLATION FAILED: failed post-install: job failed: BackoffLimitExceeded
```

**Comment by buraksekili** [comment]
> I don't think the test failure is cause by my change
> 
> ```
> W0912 16:15:18.962970    9700 warnings.go:70] spec.template.spec.containers[0].env[38].name: duplicate name "TYK_GW_SECRET"
> Error: INSTALLATION FAILED: failed post-install: job failed: BackoffLimitExceeded
> ```

@jakub-bochenski yes, you are right. your changes will not break integration tests. let's re-run it after updating the pr. we recently merged improvements regarding bootstrapping jobs, which might be the reason for the failure.

**Comment by caroltyk** [comment]
> @caroltyk bump?
> 
> Default values should be specified in values.yaml
> 
> > In an actual chart, all static default values should live in the values.yaml,
> > and should not be repeated using the default command (otherwise they would be
> > redundant). However, the default command is perfect for computed values, which
> > cannot be declared inside values.yaml.
> 
> https://helm.sh/docs/chart_template_guide/functions_and_pipelines/#using-the-default-function

Thank you @jakub-bochenski . Thank you for working with us on this. The PR is approved. After some testings it can be merged for next release.

**Pull request merged**
