### PR TITLE
[TT-10134] Fixed backward compatibility issue caused by analyticsEnabled

### PR DESCRIPTION
**Pull request by komalsukhani**
## Description

analyticsEnabled will support following values
**1. ""/ nil** 
Analytics will be enabled/disabled based on pump installations. It is supported for backward compatibility.
If `global.components.pump` is set to true, `TYK_GW_ENABLEANALYTICS` will be set to true. Otherwise `TYK_GW_ENABLEANALYTICS` will not be set.

**2. "false"**
Will set `TYK_GW_ENABLEANALYTICS` to false.

**3. true**
Will set `TYK_GW_ENABLEANALYTICS` to true.

By default, `analyticsEnabled` is set to "" for all charts.

## Related Issue

[TT-10134](https://tyktech.atlassian.net/browse/TT-10134)

## Test Coverage For This Change

Have tested tyk-oss chart with following settings
| AnalyticsEnabled | global.components.pump | Value of TYK_GW_ENABLEANALYTICS |
|------------------|---------------------------|-------------------|
| "" | true |  true |
| "" | false |  Not set |
| nil | true | true |
| nil | false | Not set |
| false | true | false | 
| true | false | true | 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

[TT-10134]: https://tyktech.atlassian.net/browse/TT-10134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jakub-bochenski** [comment]
FWIF I'm not using the umbrella charts, so this is still not backwards compatible in my case

**Comment by komalsukhani** [comment]
@jakub-bochenski When analyticsEnabled is set to false and pump is set to false or doesn't exist(in case of tyk-gateway), environment variable will not be set as before.

**Comment by jakub-bochenski** [comment]
Oh, it seems it will

Sorry, I missed that part

**Comment by komalsukhani** [comment]
No worries. I have updated the description to make it more clear.

**Review by buraksekili — APPROVED** [review]
lgtm!

**Pull request merged**
