### PR TITLE
TT-11370 feat: add configurable image for initContainers

### PR DESCRIPTION
**Pull request by unique-dominik**
## Description
We run Tyk in a scenario where only images from a dedicated OCI registry are available. Sadly this affects busybox or the initContainer as well. This PR shall make the image configurable.

🟠 I can not see any point where I could bump a version. Do pull requestors have to do that or is this automated? I mean I see the `Chart.yaml` but they were all bumped more than 2mo ago.

## Motivation and Context
When public OCI registries are forbidden/blocked, you need to pull even busybox or the initContainer images from the dedicated registry.

### Ran the chart with defaults

```
❯ pwd
/Users/medo/dev/tyk-charts/components/tyk-gateway
❯ helm template .
```

```
      initContainers:
      - name: "setup-directories"
        image: "busybox:1.32"
        command: ['sh','-c','mkdir -p apps middleware policies && touch policies/policies.json']
        workingDir: /mnt/tyk-gateway
        volumeMounts:
          - name: tyk-scratch
            mountPath: /mnt/tyk-gateway
```

### Ran template with specific values
```
helm template . --set gateway.initContainers.setupDirectories.repository=myregist.ry/repo/busybox --set gateway.initContainers.setupDirectories.tag=1.31.1
```

```
      initContainers:
      - name: "setup-directories"
        image: "myregist.ry/repo/busybox:1.31.1"
        command: ['sh','-c','mkdir -p apps middleware policies && touch policies/policies.json']
        workingDir: /mnt/tyk-gateway
        volumeMounts:
          - name: tyk-scratch
            mountPath: /mnt/tyk-gateway
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by buraksekili** [comment]
thank you @unique-dominik for the contribution!

For your question regarding:
> I can not see any point where I could bump a version. Do pull requestors have to do that or is this automated? I mean I see the Chart.yaml but they were all bumped more than 2mo ago.

The team updates Chart.yaml to trigger GH actions to release the new versions of the sub-charts and umbrella charts. So, you do not need to update Chart.yaml files.

**Review by buraksekili — APPROVED** [review]
LGTM @unique-dominik, I'll move this ticket to QA for testing. Once the QA approves this pull request, it will be merged. Thanks again!

**Comment by buraksekili** [comment]
thank you for this great contribution @unique-dominik. Your contribution will be part of the next release

**Comment by unique-dominik** [comment]
Anytime ❤️

**Pull request merged**
