### PR TITLE
TT-10658 Provide template control ingress

### PR DESCRIPTION
**Pull request by cattired**
## Description
This PR provides a template and default values for an ingress for control service.

## Related Issue
https://github.com/TykTechnologies/tyk-charts/issues/132

## Motivation and Context
The provided helm chart allows for exposing the extra container port, but there seems to be no ingress definition to setup ingress for deployment where TYK's control API needs to be accessed from remote locations.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [x] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by buraksekili** [comment]
thank you @cattired for the contribution 🙏  please feel free to tag us if you need anything or when the PR is ready

**Comment by buraksekili** [comment]
> @buraksekili Hey! I found gateway Ingress config info in other components than tyk-gateway (e.g. in Tyk MDCB Data Plane) but not in tyk-gateway where I expected it. I'm fighting with a desire to move stuff into tyk-gateway own README but maybe it deserves a dedicated ticket?

If you have the time to update the `tyk-gateway` README, we would greatly appreciate it. However, if you're unable to do so now, you can create a new issue, and we can address it in a separate pull request. Please don't feel pressured to complete the pull request immediately; take your time. Thank you!

**Comment by cattired** [comment]
Alright, to not mix too many concerns I will create a ticket and handle it once this one is settled.

**Comment by cattired** [comment]
@buraksekili Hey hey! Is there a chance to get it reviewed/merged? Can I help somehow? :)

**Review by buraksekili — COMMENTED** [review]
The PR looks great, thanks @cattired . Can you also update `values.yaml` files of `tyk-data-plane` and `tyk-oss`? So that if umbrella charts are in use, they can also benefit from this new capability.

**Comment by cattired** [comment]
@buraksekili Done ;)

**Review by buraksekili — COMMENTED** [review]
Looks good to me! However, before proceeding with the merge, could you kindly address the linter issue? Additionally, have you tested the pull request? If so, could you please provide the steps you took? I am also conducting tests on my end.

**Comment by cattired** [comment]
@buraksekili Sorry for the deferred response: I got sick. I hope the linter is happy now. Let me explain how I tested the PR, altho I'm not sure this is what you want to know. The values I used are approx like those in the attached screen.

Screenshot-from-2023-12-05-00-13-14-png-2488×1415-

Once the ingress came online I used 

curl --silent --show-error --fail-with-body https://xxx-control.xxx.com/hello

which returns

{"status":"pass","version":"5.1.2","description":"Tyk GW","details":{"redis":{"status":"pass","componentType":"datastore","time":"2023-12-04T23:21:22Z"}}}

Is this what you are asking about or is there some workflow I should have followed?

Cheers

**Comment by buraksekili** [comment]
@cattired no worries, and take care! 
thank you for the detailed response 🙏 I will run some tests as well then proceed with the next steps.

**Comment by buraksekili** [comment]
@cattired thank you again for your contribution. our QA scheduled testing for this PR. Could you please kindly resolve the conflict in the README? If you have no availability, please let me know and I can resolve it. Thank you again for your contribution.

**Comment by buraksekili** [comment]
@cattired thank you very much for your contribution. The PR has been merged as part of #228. Our QA could not merge your PR as it includes some conflicts and i am going to close this PR in favor of #228. Again, thank you for this contribution

**Pull request closed without merging**
