### PR TITLE
TT-12112 Add the value annotations to tyk-stack and component helm charts

### PR DESCRIPTION
**Pull request by mgnisia**
## Description

Add `annotations` variable to the values.yaml file of all relevant helm charts

## Motivation and Context

To support an automated reloading of the gateway or other components of the tyk stack a common approach is to utilize tools like reloader. Currently the helm charts don't support any kind of annotations on the deployment level.

## Test Coverage For This Change

I have been templating the helm charts on my machine (`helm template`) with: 

```
annotations: {}
```

```
annotations:
  app: "someAnnotation"
```

The templating worked without any issues.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [ ] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by caroltyk** [comment]
Thank you @mgnisia for your contribution. We will review this shortly.

**Comment by mgnisia** [comment]
@caroltyk Hi Carol, could you maybe take another look? that would be awesome.

**Comment by caroltyk** [comment]
Hi @mgnisia The PR looks good to me but I'll pass this to the engineers and QA for testing first. Let me update here when it is planned for release.

**Review by buraksekili — COMMENTED** [review]
thank you @mgnisia  for the great contribution! The PR looks great to me!
However, bumping `version` of the chart triggers release action. Can you please not bump versions of the charts?

**Comment by mgnisia** [comment]
Thanks for the update 🙂 will revert the version change beginning of next week 👍🏻

**Comment by mgnisia** [comment]
Good morning @buraksekili revert the changes. It would be awesome if you cloud take another look. 👀

**Review by buraksekili — APPROVED** [review]
looks great to me @mgnisia! thanks for the contribution 🙏  I'll hand over the PR for testing, which will be merged once the testing is finished. I'll let you know if any questions arise during the testing process. once again, thank you for your time and contribution

**Comment by bojantyk** [comment]
LGTM! @buraksekili  we should proceed with merging this PR 
Thanks,

**Comment by mgnisia** [comment]
@buraksekili can you foresee when this PR will be merged?

**Comment by buraksekili** [comment]
@mgnisia thanks for your contribution 🏅  your contribution is going to be released within the next release.

**Pull request merged**
