### PR TITLE
TT-13451 Add missing config arg to support operator v0.18.0

### PR DESCRIPTION
**Pull request by lboynton**
## Description

Without this, the liveness and readiness probes fail and you end up in a CrashLoopBackoff

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] Documentation updates or improvements.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
     - [ ] I have manually updated the README(s)/documentation accordingly.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by buraksekili** [comment]
@lboynton thanks for raising this!

With the release of v1.0.0, we've enhanced the capabilities of the Tyk Operator. However, the Operator currently does not accept the `--config` flag as an argument, so the solution proposed in the PR will not work for v1.0.0.

Additionally, the Tyk Operator uses default values defined in the `ControllerManagerConfiguration` here: https://github.com/TykTechnologies/tyk-charts/blob/37d55acbcc7cb5af4466ffad4650e49930c7aa02/components/tyk-operator/templates/all.yaml#L395-L406 

Therefore, providing incorrect Manager configuration may not cause a problem unless Operator misses some configs.

Could you please share any logs or findings with me for further investigation?

In the meantime, the following arguments can be added:
```yaml
      - args:
        - --leader-elect
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        command:
        - /manager
```

These args for specific to Tyk Operator v1.0.0. In the meantime, the team internally works on this to make this process smoother.

**Comment by lboynton** [comment]
Thanks @buraksekili, this makes more sense. I was attempting to use `v0.18.0` of the operator initially to make the upgrade smoother. So possibly it's only an issue with that version.

**Comment by buraksekili** [comment]
Oh I see - this happened during the upgrade, thanks for the input! 
I'll also update the team accordingly. please let me know and feel free to tag me for any inquiries.

**Comment by lboynton** [comment]
Thanks. I initially tried `v1.0.0` with a valid license key passed to `global.license.operator`, but got the following error in the operator logs:
```
{"level":"error","ts":"2024-10-31T13:29:46Z","logger":"license","msg":"failed to validate license","error":"kindly specify a valid license key.","stacktrace":"github.com/TykTechnologies/tyk-operator/pkg/environment.(*License).validateKey\n\t/workspace/pkg/environment/license.go:50\ngithub.com/TykTechnologies/tyk-operator/pkg/environment.(*License).StartPeriodicValidation\n\t/workspace/pkg/environment/license.go:84"}
```
Still trying to work out if I'm passing it in wrong or if it's not being passed through correctly.

**Comment by buraksekili** [comment]
Hmm, I see. In the meantime, could you please try setting the TYK_OPERATOR_LICENSEKEY environment variable explicitly for the Operator Manager pod, if passing the license directly is acceptable in your k8s environment?

**Comment by lboynton** [comment]
> Hmm, I see. In the meantime, could you please try setting the TYK_OPERATOR_LICENSEKEY environment variable explicitly for the Operator Manager pod, if passing the license directly is acceptable in your k8s environment?

Thanks this works. It also looks like you can edit the `tyk-operator-conf` secret and add `TYK_OPERATOR_LICENSEKEY` as a key. Perhaps I should raise a separate bug to say that the tyk-oss chart doesn't set the license key?

**Comment by buraksekili** [comment]
glad it worked! thanks for your collaboration. 

Feel free to create a ticket. I'll also consider our discussion for planning and further investigation. 
Thanks once again for your time and collaboration 🙏

**Comment by buraksekili** [comment]
Thanks for your time @lboynton , i am closing this PR as of now and the team will work on the issue to update operator deployment manifest based on the new args. Thanks again for raising this!

**Pull request closed without merging**
